siwecos.settings:
  type: config_object
  mapping:
    api_url:
      type: uri
      label: 'API Url'
    api_token:
      type: string
      label: 'API Token'
    domain:
      type: uri
      label: 'Domain'
    domain_token:
      type: string
      label: 'Domain Token'
    email:
      type: mail
      label: 'Email'
    password:
      type: string
      label: 'Password'
